### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by hangryfabian** [dollars0427/hologram-image-upload#11]
Hey! This looks great - when trying to implement I am getting an error - any idea?

[22:04:14] Browserify ErrorMessage 
C:\GitHub\MyProject\node_modules\hologram-image-upload\index.js:1
import Hologram from './dist/Hologram';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by falconshark** [comment]
Hello hangryfabian,
It is because that Browserify do not support ES6 module syntax with out babel, so it will throw error.
I will try to fix it.

**Comment by falconshark** [comment]
Bug fixed.
Please using latest version of Hologram: hologram-image-upload@2.6.3
Thank's for your report :)

**Comment by hangryfabian** [comment]
Thanks for the very quick fix! It is now working.
