### ISSUE TITLE
How can I pass multiple images with prop

### ISSUE THREAD

**Issue by CodeByRahulSaini** [dollars0427/hologram-image-upload#12]
Actually, I am making a product edit page. When I am adding pages I am adding images with hologram. But at product editing page how can I show auto-filled images

**Comment by falconshark** [comment]
Dear IMRahulSaini, 
I'm sorry that Hologram do not have auto-fill function currently. I will try to add this function as soon as possible. (Maybe Tomorrow).

**Comment by falconshark** [comment]
Added defaultFiles props to Hologram now. You can pass a files array like this to set default images of Dropzone:

```jsx
<Hologram defaultFiles={[{name: 'dummy.jpg', url: 'https://s3-ap-southeast-1.amazonaws.com/dummy/dummy.jpg', type: 'image/jpeg'}]}/>
```

Please using latest version of Hologram: hologram-image-upload@2.7.3.
Thank's for your report :)

**Comment by CodeByRahulSaini** [comment]
Thanks man :+1:
