### ISSUE TITLE
Forgot to remove resolve the customUpload promise

### ISSUE THREAD

**Issue by midyan** [dollars0427/hologram-image-upload#7]
In the Hologram.js component, I forgot to resolve the promise on this [line](https://github.com/dollars0427/hologram-image-upload/blob/master/src/components/Hologram.js#L169).

Just swap console.log for reject

**Comment by midyan** [comment]
The PR #8 will solve this issue and issue #9 

🚀

**Comment by falconshark** [comment]
Pull request merged. Thank you!
